image: Visual Studio 2017

install:
 - SET PATH=C:\cygwin64\bin;%PATH%
 - choco install mingw
 - C:\tools\mingw64\bin
 - SET PATH=C:\tools\mingw64\bin;%PATH%
 - mingw-get install g++

build_script:
 - g++ src/zopfli/{blocksplitter,cache,deflate,gzip_container,hash,katajainen,lz77,squeeze,tree,util,zlib_container,zopfli_lib}.c src/zopflipng/*.cc src/zopflipng/lodepng/*.cpp -O2 -W -Wall -Wextra -Wno-unused-function -ansi -pedantic -o zopflipng
