configuration: Release

## Sets up two jobs, one with cmake (MSVC) and one with cygwin64
environment:
  matrix:
   - compiler: cmake
     image: Visual Studio 2019
     install: cd %APPVEYOR_BUILD_FOLDER% & mkdir cmake_build & cd cmake_build & cmake --version & cmake -A x64 c:\projects\zopfli
     build:
       project: zopfli.sln
   - compiler: cygwin64
     image: Visual Studio 2017
     install: SET PATH=C:\cygwin64\bin;%PATH%
     build_script: x86_64-pc-cygwin-g++.exe src/zopfli/{blocksplitter,cache,deflate,gzip_container,hash,katajainen,lz77,squeeze,tree,util,zlib_container,zopfli_lib}.c src/zopflipng/*.cc src/zopflipng/lodepng/*.cpp -O2 -W -Wall -Wextra -Wno-unused-function -ansi -pedantic -o zopflipng
 
## Publishes artifacts to AppVeyor
artifacts:
 - path: cmake_build\Release\zopflipng.exe
   name: zopflip-x86_64-cmake
 - path: zopflipng.exe
   name: zopflipng-x86_64-cygwin64
