image: Visual Studio 2017

environment:
  matrix:
    include:
    - target: zopfli
    - target: zopflipng

build_script:
 - cmake $target
 
artifacts:
 - path: \**\zopflipng.exe
   name: zopflipng-x86_64-cmake
