image: Visual Studio 2017

configuration: Release

environment:
  matrix:
   - target: zopfli

before_build:
- cmd: |-
    cd %APPVEYOR_BUILD_FOLDER%
    mkdir cmake_build
    cd cmake_build
    cmake --version
    cmake c:\projects\zopfli

# Build aom with Visual Studio 2017
build:
  project: C:\projects\zopfli\cmake_build\%target%.sln
 
artifacts:
 - path: \**\zopflipng.exe
   name: zopflipng-x86_64-cmake
